package StringLengthApp;


/**
* StringLengthApp/StringLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringLengthApp.idl
* Thursday, November 26, 2015 6:56:16 PM MSK
*/

public interface StringLength extends StringLengthOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringLength
