package StringLengthApp;

/**
* StringLengthApp/StringLengthHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringLengthApp.idl
* Thursday, November 26, 2015 6:56:16 PM MSK
*/

public final class StringLengthHolder implements org.omg.CORBA.portable.Streamable
{
  public StringLengthApp.StringLength value = null;

  public StringLengthHolder ()
  {
  }

  public StringLengthHolder (StringLengthApp.StringLength initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringLengthApp.StringLengthHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringLengthApp.StringLengthHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringLengthApp.StringLengthHelper.type ();
  }

}
