package StringLengthApp;


/**
* StringLengthApp/StringLengthPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringLengthApp.idl
* Thursday, November 26, 2015 6:56:16 PM MSK
*/

public abstract class StringLengthPOA extends org.omg.PortableServer.Servant
 implements StringLengthApp.StringLengthOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getStringLength", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // StringLengthApp/StringLength/getStringLength
       {
         String str = in.read_wstring ();
         String $result = null;
         $result = this.getStringLength (str);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // StringLengthApp/StringLength/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StringLengthApp/StringLength:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public StringLength _this() 
  {
    return StringLengthHelper.narrow(
    super._this_object());
  }

  public StringLength _this(org.omg.CORBA.ORB orb) 
  {
    return StringLengthHelper.narrow(
    super._this_object(orb));
  }


} // class StringLengthPOA
