package StringLengthApp;


/**
* StringLengthApp/StringLengthOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringLengthApp.idl
* Thursday, November 26, 2015 6:56:16 PM MSK
*/

public interface StringLengthOperations 
{
  String getStringLength (String str);
  void shutdown ();
} // interface StringLengthOperations
