package StringLengthApp;


/**
* StringLengthApp/StringLengthHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringLengthApp.idl
* Thursday, November 26, 2015 6:56:16 PM MSK
*/

abstract public class StringLengthHelper
{
  private static String  _id = "IDL:StringLengthApp/StringLength:1.0";

  public static void insert (org.omg.CORBA.Any a, StringLengthApp.StringLength that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StringLengthApp.StringLength extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StringLengthApp.StringLengthHelper.id (), "StringLength");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StringLengthApp.StringLength read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StringLengthStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StringLengthApp.StringLength value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StringLengthApp.StringLength narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringLengthApp.StringLength)
      return (StringLengthApp.StringLength)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringLengthApp._StringLengthStub stub = new StringLengthApp._StringLengthStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static StringLengthApp.StringLength unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringLengthApp.StringLength)
      return (StringLengthApp.StringLength)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringLengthApp._StringLengthStub stub = new StringLengthApp._StringLengthStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
